### PR TITLE
Add a Docker images to the projet

### PR DESCRIPTION
**Pull request by StephenSorriaux**
Hello,

I played a little with your project and created a Docker image to use it easily.

If the PR is ok, please tell me to which Docker account it would be associated so that I can update the README.

### CODE REVIEW

**Comment by xep624** [comment]
Good idea! I'll test it and get back to you soon.

**Comment by xep624** [comment]
Thanks Stephen for this PR! I've just pushed the image to rzepsky/dumpsterdiver. Please update the README file and I'll merge it

**Comment by StephenSorriaux** [comment]
Great, I just updated the README

**Comment by securing** [comment]
Thank you Stephen! I want to add a "special thanks" section to README file - don't you mind I'll put your name there? You're the first contributor in this little project :)

**Comment by StephenSorriaux** [comment]
Oh thanks, sure go ahead!

**Pull request merged**
